// Banco de preguntas multiple choice para el parcial.
// Formato: { u: unidad, q: enunciado, o: [[texto, 1 si es correcta / 0 si no], ...], e: explicación }
// Cada pregunta puede tener 0, 1, 2 o 3 opciones correctas (nunca todas).
window.EXAM_BANK = {

  // ======================= FÁCIL =======================
  facil: [
    { u: 1, q: 'Según la definición integral de software, ¿qué elementos forman parte del software?',
      o: [['Los programas que se ejecutan', 1], ['La documentación de usuario', 1], ['Los archivos de configuración', 1], ['El hardware sobre el que corre', 0]],
      e: 'El software es el conjunto completo: programas, estructuras de datos, contenido, configuración, documentación técnica y de usuario. El hardware no es software.' },
    { u: 1, q: 'Respecto del desgaste y el deterioro del software, ¿qué afirmaciones son correctas?',
      o: [['El software se desgasta con el uso igual que el hardware', 0], ['Un binario que no se toca en veinte años es idéntico bit por bit al primer día', 1], ['La curva de fallos del software es la curva de la bañera', 0], ['Cada cambio que se introduce puede agregar defectos nuevos', 1]],
      e: 'El software no se desgasta (no tiene materia), pero se deteriora: cada cambio introduce defectos y el piso de la curva sube. La curva de la bañera es la del hardware.' },
    { u: 1, q: '¿Cuándo y dónde se propuso formalmente el término “Ingeniería de Software”?',
      o: [['En 1968, en una conferencia auspiciada por la OTAN', 1], ['En 1975, en una conferencia de la IEEE', 0], ['En 2001, junto con el Manifiesto Ágil', 0], ['En 1968, en una conferencia auspiciada por la ONU', 0]],
      e: 'Fue en 1968, en la conferencia de la OTAN, como respuesta a la crisis del software.' },
    { u: 1, q: '¿Qué palabras forman parte de la definición IEEE de Ingeniería de Software (“enfoque ... al desarrollo, operación y mantenimiento”)?',
      o: [['Sistemático', 1], ['Disciplinado', 1], ['Cuantificable', 1], ['Automatizado', 0]],
      e: 'La definición IEEE habla de un enfoque sistemático, disciplinado y cuantificable.' },
    { u: 1, q: 'Según la Ley de Brooks, agregar programadores a un proyecto atrasado...',
      o: [['Lo acelera en proporción a la gente agregada', 0], ['Lo atrasa más', 1], ['No tiene ningún efecto sobre el plazo', 0], ['Reduce la cantidad de canales de comunicación', 0]],
      e: 'Lo atrasa más: los nuevos necesitan capacitación y los canales de comunicación crecen cuadráticamente (N(N-1)/2).' },
    { u: 1, q: '¿Cuáles de estos enunciados son mitos DEL CLIENTE?',
      o: [['“Los cambios son baratos porque el software es flexible”', 1], ['“Un enunciado general de los objetivos alcanza para empezar a programar”', 1], ['“Cuando el programa funciona el trabajo está terminado”', 0], ['“Un manual de estándares completo garantiza que el equipo construya bien”', 0]],
      e: 'Los mitos del cliente nacen de no entender el costo de la ambigüedad y del cambio tardío. “El programa funciona = terminado” es de desarrollador; “manual de estándares” es de gestión.' },
    { u: 1, q: 'Sobre la crisis del software, ¿qué afirmaciones son correctas?',
      o: [['Fue un evento puntual ocurrido en un único proyecto de 1968', 0], ['Se produjo porque el software avanzaba más rápido que el hardware', 0], ['Quedó resuelta definitivamente con la conferencia de la OTAN', 0], ['Fue un problema solo de costos; la calidad de los sistemas era buena', 0]],
      e: 'Ninguna es correcta. La crisis fue la constatación de un desfasaje: el hardware crecía exponencialmente y la capacidad de construir software confiable mucho más despacio. Los síntomas: entregas tarde, sobrecostos, sistemas que no hacían lo necesario y mala calidad.' },
    { u: 2, q: 'Un objeto está compuesto por:',
      o: [['Estado', 1], ['Comportamiento', 1], ['Identidad', 1], ['Herencia', 0]],
      e: 'Estado (lo que sabe), comportamiento (lo que hace) e identidad (lo que lo distingue de otros). La herencia es una relación entre clases.' },
    { u: 2, q: '¿Cómo se representa la COMPOSICIÓN en UML?',
      o: [['Con un rombo hueco del lado del todo', 0], ['Con un triángulo hueco hacia la superclase', 0], ['Con una línea punteada y flecha abierta', 0], ['Con una línea discontinua y punta de flecha vacía', 0]],
      e: 'Ninguna es correcta. La composición se dibuja con un rombo RELLENO del lado del todo. El rombo hueco es agregación, el triángulo es generalización, la punteada es dependencia y la discontinua con punta vacía es realización.' },
    { u: 2, q: '¿Cuáles son elementos MAYORES del modelo de objetos?',
      o: [['Abstracción', 1], ['Encapsulamiento', 1], ['Persistencia', 0], ['Concurrencia', 0]],
      e: 'Los mayores son abstracción, encapsulamiento, modularidad y jerarquía. Tipificación, concurrencia y persistencia son elementos menores.' },
    { u: 2, q: '¿Qué categorías conviene buscar en un enunciado para detectar clases?',
      o: [['Lugares', 1], ['Transacciones o eventos', 1], ['Roles que cumplen personas', 1], ['Algoritmos de ordenamiento', 0]],
      e: 'Las cinco categorías: roles de personas, roles de organizaciones, lugares, cosas y transacciones o eventos.' },
    { u: 3, q: '¿Cuáles son actividades estructurales genéricas según Pressman?',
      o: [['Comunicación', 1], ['Planeación', 1], ['Mantenimiento', 0], ['Auditoría', 0]],
      e: 'Las cinco son: comunicación, planeación, modelado, construcción y despliegue.' },
    { u: 3, q: '¿Cuál de estos es un valor del Manifiesto Ágil tal como está escrito?',
      o: [['Individuos e interacciones sobre procesos y herramientas', 1], ['Documentación extensiva sobre software funcionando', 0], ['Seguir un plan sobre respuesta ante el cambio', 0], ['Negociación contractual sobre colaboración con el cliente', 0]],
      e: 'Las otras tres están invertidas: el manifiesto valora software funcionando, respuesta ante el cambio y colaboración con el cliente por encima de lo otro.' },
    { u: 3, q: '¿Cuáles son responsabilidades (roles) definidas en el Scrum Team?',
      o: [['Product Owner', 1], ['Scrum Master', 1], ['Developers', 1], ['Project Manager', 0]],
      e: 'Scrum define tres responsabilidades: Developers, Product Owner y Scrum Master. No hay Project Manager.' },
    { u: 3, q: '¿Cuánto dura el Daily Scrum?',
      o: [['15 minutos', 1], ['1 hora', 0], ['30 minutos', 0], ['Lo que dure el Sprint', 0]],
      e: 'El Daily Scrum dura 15 minutos, participan los Developers y se hace cada día.' },
    { u: 3, q: '¿Cuáles son fases del Proceso Unificado?',
      o: [['Inicio', 1], ['Elaboración', 1], ['Pruebas', 0], ['Análisis', 0]],
      e: 'Las cuatro fases son Inicio, Elaboración, Construcción y Transición. Análisis y Prueba son FLUJOS de trabajo, no fases.' },
    { u: 4, q: 'En el Proceso Unificado, un “trabajador” es...',
      o: [['Una persona concreta del organigrama', 0], ['Un cargo que obligatoriamente hay que contratar', 0], ['Un empleado de la empresa cliente', 0], ['Un producto del proceso, como un modelo o documento', 0]],
      e: 'Ninguna es correcta. Un trabajador es un ROL: define comportamiento y responsabilidades. Un producto del proceso es un artefacto.' },
    { u: 5, q: '¿Cuáles de estos son requisitos NO funcionales?',
      o: [['“El sistema debe responder a una consulta en menos de 2 segundos”', 1], ['“El sistema debe permitir registrar una venta”', 0], ['“El sistema debe cumplir con GDPR”', 1], ['“El sistema debe permitir al cliente verificar el estado de su pedido”', 0]],
      e: 'Los no funcionales describen CÓMO se comporta el sistema (rendimiento, legales, etc.). Registrar una venta o consultar un pedido son funciones (QUÉ hace).' },
    { u: 5, q: '¿Cuál es el formato de una user story?',
      o: [['Como [tipo de usuario], quiero [una acción] para [obtener un beneficio]', 1], ['Si [condición], el sistema [acción]', 0], ['El actor [nombre] ejecuta [caso de uso]', 0], ['Precondición, flujo básico y postcondición', 0]],
      e: '“Como..., quiero..., para...”. La última opción describe la estructura de un caso de uso, no una user story.' },
    { u: 5, q: '¿Cuáles son procesos de la Ingeniería de Requerimientos?',
      o: [['Elicitación', 1], ['Especificación', 1], ['Despliegue', 0], ['Codificación', 0]],
      e: 'Los cinco procesos: elicitación, análisis, especificación, validación y administración.' }
  ],

  // ======================= MEDIO =======================
  medio: [
    { u: 1, q: 'Sobre los atributos de calidad, ¿qué afirmaciones son correctas?',
      o: [['Más seguridad suele implicar menos usabilidad', 1], ['Más eficiencia suele implicar menos mantenibilidad', 1], ['Un buen ingeniero maximiza los cuatro atributos a la vez', 0], ['Más mantenibilidad (capas de abstracción) puede costar eficiencia', 1]],
      e: 'Los atributos compiten entre sí: el ingeniero no los maximiza todos, los balancea según lo que el sistema necesita.' },
    { u: 1, q: '¿Qué ejemplos cumplen el doble rol de PRODUCTO y VEHÍCULO simultáneamente, según el material?',
      o: [['PostgreSQL', 1], ['Un navegador web', 1], ['Un monitor LCD', 0], ['Un teclado mecánico', 0]],
      e: 'PostgreSQL es producto para el DBA y vehículo para las apps; el navegador, producto para quien navega y vehículo para las apps web. Monitor y teclado son hardware.' },
    { u: 1, q: '¿Cuál es la distinción FUNDAMENTAL entre software genérico y a medida?',
      o: [['Quién controla los requisitos', 1], ['El lenguaje de programación utilizado', 0], ['El precio de la licencia', 0], ['Si corre en la web o en escritorio', 0]],
      e: 'En el genérico decide la organización que lo vende; en el a medida, el cliente que lo encarga (típicamente vía una ERS).' },
    { u: 1, q: 'Sobre las decisiones con software heredado, ¿qué es correcto?',
      o: [['Son decisiones técnicas que toma el programador', 0], ['Son decisiones estratégicas', 1], ['“Envolver” conviene si funciona bien pero hay que adaptarlo a interfaces nuevas', 1], ['“Reescribir” conviene cuando la lógica de negocio ya no es válida', 0]],
      e: 'Son estratégicas. Reescribir conviene cuando la lógica de negocio SIGUE siendo válida pero la implementación es insostenible.' },
    { u: 1, q: '¿Cuáles de estas afirmaciones son REALIDADES (y no mitos)?',
      o: [['Entre el 50% y el 70% del esfuerzo se gasta después de la primera entrega', 1], ['La documentación es lo que hace posible el mantenimiento', 1], ['Lo único entregable es el código ejecutable', 0], ['Las pruebas no son un producto del trabajo', 0]],
      e: 'Las dos primeras son las realidades que desmienten los mitos del desarrollador. Modelo, documentación y pruebas también son productos del trabajo.' },
    { u: 1, q: 'Un cambio de requisitos después de la entrega, comparado con hacerlo durante la captura de requisitos, cuesta:',
      o: [['Lo mismo, porque el software es flexible', 0], ['Entre 2 y 5 veces más', 0], ['Menos, porque el código ya existe', 0], ['Entre 10 y 20 veces más', 0]],
      e: 'Ninguna es correcta: puede costar entre 50 y 100 veces más (hay que rehacer análisis, diseño, código, pruebas, documentación y migrar datos).' },
    { u: 1, q: '¿Cuáles son los retos fundamentales de la ingeniería de software en el siglo XXI?',
      o: [['Heterogeneidad', 1], ['Entrega', 1], ['Confianza', 1], ['Portabilidad', 0]],
      e: 'Heterogeneidad, entrega y confianza. No son independientes: son proyecciones de gestionar la complejidad del software moderno.' },
    { u: 1, q: '¿Qué ejemplos corresponden a software EMPOTRADO?',
      o: [['El firmware de un microondas', 1], ['Un marcapasos', 1], ['Un compilador de Java', 0], ['Gmail', 0]],
      e: 'El empotrado vive dentro de un dispositivo con restricciones de memoria, energía y tiempo real. El compilador es de sistemas y Gmail es web.' },
    { u: 2, q: 'Sobre agregación y composición, ¿qué es correcto?',
      o: [['En la agregación las partes pueden existir independientemente del todo', 1], ['En la composición, si se destruye el todo se destruyen las partes', 1], ['Equipo–Jugador es un ejemplo típico de composición', 0], ['Factura–DetalleDeFactura es un ejemplo típico de agregación', 0]],
      e: 'Equipo–Jugador es agregación (el jugador existe sin el equipo). Factura–Detalle es composición (el detalle no tiene sentido sin la factura).' },
    { u: 2, q: '¿Qué afirmaciones describen al ENCAPSULAMIENTO?',
      o: [['Separa la interfaz de la implementación', 1], ['Permite cambiar la implementación interna sin afectar a quien usa la interfaz', 1], ['Hace que todas las clases hereden de una superclase común', 0], ['Consiste en dividir en módulos cohesivos y débilmente acoplados', 0]],
      e: 'Dividir en módulos cohesivos y débilmente acoplados es MODULARIDAD, no encapsulamiento.' },
    { u: 1, q: 'Sobre los principios del modelado, ¿qué es correcto?',
      o: [['Un único modelo bien hecho alcanza para cualquier sistema no trivial', 0], ['La elección de qué modelos crear condiciona cómo se acomete el problema', 1], ['Todo modelo puede expresarse en distintos niveles de precisión', 1], ['Los mejores modelos están ligados a la realidad', 1]],
      e: 'El cuarto principio dice lo contrario: un único modelo NO es suficiente; se usa un conjunto de modelos casi independientes.' },
    { u: 2, q: 'Sobre la relación de DEPENDENCIA, ¿qué es correcto?',
      o: [['Se dibuja con línea punteada y flecha abierta', 1], ['Es la relación más débil', 1], ['Implica que una clase posee a la otra de forma permanente', 0], ['Típicamente una clase usa a otra como parámetro de un método', 1]],
      e: 'Es la relación más débil: un cambio en una clase puede afectar a otra SIN vínculo permanente.' },
    { u: 2, q: 'En los patrones de Coad, la relación “Libro – Ejemplar” corresponde a:',
      o: [['Ítem – ÍtemEspecífico', 1], ['Transacción – TransacciónSubsiguiente', 0], ['Participante – Transacción', 0], ['Actor – Participante', 0]],
      e: 'El Libro es el ítem general y el Ejemplar es la instancia concreta (ÍtemEspecífico).' },
    { u: 3, q: 'Sobre el Scrum Master, ¿qué es correcto?',
      o: [['Es el jefe del equipo', 0], ['Crea y ordena el Product Backlog', 0], ['Define y comunica el Objetivo del Producto', 0], ['Es quien decide qué hace cada Developer', 0]],
      e: 'Ninguna. El SM es facilitador: hace que Scrum se entienda y practique, ayuda a auto-gestionarse y elimina impedimentos. El Backlog y el Objetivo del Producto son del Product Owner, y el equipo decide internamente quién hace qué.' },
    { u: 3, q: '¿Cuál de estas es una actividad SOMBRILLA?',
      o: [['Gestión del riesgo', 1], ['Construcción', 0], ['Despliegue', 0], ['Comunicación', 0]],
      e: 'Construcción, despliegue y comunicación son actividades estructurales. Las sombrilla (riesgo, calidad, configuración, medición...) corren durante todo el proyecto.' },
    { u: 3, q: 'El Proceso Unificado es una especialización muy elaborada de...',
      o: [['El enfoque en cascada', 0], ['La ingeniería basada en componentes (CBSE)', 0], ['El modelo de métodos formales', 0], ['El modelo DRA', 0]],
      e: 'Ninguna. El PU especializa el paradigma de DESARROLLO ITERATIVO.' },
    { u: 3, q: '¿Qué pares artefacto – compromiso de Scrum son correctos?',
      o: [['Product Backlog – Objetivo del Producto', 1], ['Sprint Backlog – Definición de Hecho', 0], ['Increment – Objetivo del Sprint', 0], ['Increment – Definición de Hecho', 1]],
      e: 'Product Backlog → Objetivo del Producto; Sprint Backlog → Objetivo del Sprint; Increment → Definición de Hecho.' },
    { u: 3, q: 'Sobre la fase de ELABORACIÓN del PU, ¿qué es correcto?',
      o: [['Desarrolla la línea base de la arquitectura', 1], ['Al final, el director de proyecto puede estimar los recursos para comprometerse al desarrollo', 1], ['Es la fase en la que se emplea el grueso de los recursos', 0], ['Termina en la capacidad operativa inicial', 0]],
      e: 'El grueso de los recursos se emplea en Construcción, que termina en la capacidad operativa inicial.' },
    { u: 5, q: 'Sobre validación y verificación, ¿qué es correcto?',
      o: [['Son sinónimos', 0], ['Validación responde “¿estamos construyendo lo correcto?”', 1], ['Verificación responde “¿estamos construyendo lo correcto?”', 0], ['La validación se hace únicamente después de la entrega', 0]],
      e: 'Validación = ¿construimos lo correcto? Verificación = ¿lo construimos correctamente? Validar conviene ANTES del diseño e implementación.' },
    { u: 5, q: 'Sobre la relación <<include>> entre casos de uso, ¿qué es correcto?',
      o: [['El comportamiento incluido siempre se ejecuta', 1], ['La flecha va desde el caso base hacia el incluido', 1], ['El caso base no sabe que incluye a otro', 0], ['Sirve para factorizar variantes que ocurren bajo condición', 0]],
      e: 'En la inclusión el base lo llama EXPLÍCITAMENTE. Lo condicional y “el base ni se entera” corresponde a <<extend>>.' }
  ],

  // ======================= DIFÍCIL =======================
  dificil: [
    { u: 1, q: 'Sobre la curva de fallos del software, ¿qué afirmaciones son correctas?',
      o: [['Tras cada cambio la tasa de fallos sube', 1], ['Después de corregir, la tasa vuelve exactamente al nivel previo', 0], ['El piso de la curva se va elevando cambio tras cambio', 1], ['El deterioro se explica por la degradación física de los medios de almacenamiento', 0], ['La conclusión práctica es que la mantenibilidad es un atributo de calidad clave', 1]],
      e: 'No vuelve al nivel anterior: queda un poco más arriba. El deterioro no es físico, es la degradación de la estructura interna por los cambios.' },
    { u: 1, q: '¿Qué consecuencias se derivan de que el software “se desarrolla, no se manufactura”?',
      o: [['La calidad se puede inspeccionar al final, como en una fábrica', 0], ['El mayor costo está en fabricar las copias', 0], ['Las pruebas deben dejarse para la última etapa', 0], ['Una línea de montaje abarata el producto por volumen', 0], ['El costo de un defecto es el mismo sin importar cuándo se detecta', 0]],
      e: 'Ninguna. Las consecuencias reales: es humano-intensivo, la calidad se construye durante todo el proceso, se prueba desde el principio y el costo de un defecto crece con el tiempo.' },
    { u: 1, q: 'Sobre la reutilización en software, ¿qué es correcto?',
      o: [['La lógica de negocio específica de cada organización suele reutilizarse masivamente', 0], ['Reutilizar implica entender, adaptar, confiar y quedar acoplado a la evolución del componente', 1], ['La reutilización efectiva es una decisión de arquitectura', 1], ['Reutilizar siempre trae menos problemas que escribir código propio', 0], ['Frameworks como Django o Spring son ejemplos de lo que sí se reutiliza', 1]],
      e: 'La lógica de negocio se sigue construyendo a medida, y un equipo que reutiliza mal puede terminar con más problemas que uno que escribió su propio código.' },
    { u: 1, q: 'Sobre proceso, métodos y herramientas, ¿qué es correcto?',
      o: [['El proceso es el aglutinante que une las capas', 1], ['Los métodos responden “¿con qué se hacen las cosas más eficientemente?”', 0], ['Las herramientas incluyen sistemas CASE', 1], ['La capa base de toda la estructura son las herramientas', 0], ['Los métodos responden “¿en qué orden ocurren las cosas?”', 0]],
      e: '“¿Con qué?” = herramientas; “¿en qué orden?” = proceso; “¿cómo se hace?” = métodos. La capa base es el compromiso organizacional con la calidad.' },
    { u: 1, q: 'Clasificá el enunciado: “Si el proyecto está atrasado, sumemos dos programadores y listo”.',
      o: [['Es un mito de gestión', 1], ['Es un mito del cliente', 0], ['Es un mito del desarrollador', 0], ['Nace de subestimar todo lo que viene después de que el código anda', 0], ['Nace de buscar un atajo que sustituya al trabajo', 1]],
      e: 'Mito de gestión: su raíz es la presión por plazos y la búsqueda de un atajo. “Subestimar lo que viene después” es la raíz de los mitos del desarrollador.' },
    { u: 1, q: 'Sobre el software heredado, ¿qué es correcto?',
      o: [['Según los estándares modernos tiene alta calidad', 0], ['Es poco confiable porque nadie lo entiende del todo', 0], ['Decidir reemplazarlo es siempre una decisión técnica del equipo', 0], ['Siempre conviene reescribirlo en tecnología actual', 0], ['Su documentación suele ser completa y actualizada', 0]],
      e: 'Ninguna. La paradoja: tiene baja calidad según estándares modernos pero es CONFIABLE por años de defectos corregidos. Las decisiones son estratégicas y dependen del caso; la documentación suele ser pobre.' },
    { u: 1, q: 'Sobre BPMN, ¿qué es correcto?',
      o: [['Es un estándar de la IEEE', 0], ['El evento de fin se representa con un círculo lleno', 1], ['Las puertas (decisiones) se representan con rectángulos', 0], ['Las actividades se representan con rombos', 0], ['Es un puente entre analistas de negocio y arquitectos de software', 1]],
      e: 'BPMN es estándar de la OMG. Actividades = rectángulos; puertas = rombos.' },
    { u: 5, q: '¿Cuáles son reglas de oro de Schneiderman para interfaces?',
      o: [['Reducir la carga de memoria del usuario', 1], ['Permitir acciones reversibles (Deshacer)', 1], ['Mostrar códigos de error numéricos para mayor precisión', 0], ['Usar secuencias inflexibles para guiar al usuario', 0], ['Esconder las opciones en menús profundos para no saturar', 0]],
      e: 'Nunca usar códigos de error tipo “Error #4027”; el usuario debe tener el control (sin secuencias forzadas) y las opciones deben estar visibles.' },
    { u: 2, q: 'Sobre la perspectiva orientada a objetos frente a la algorítmica, ¿qué es correcto?',
      o: [['La algorítmica usa como bloque de construcción el procedimiento o función', 1], ['La algorítmica produce sistemas más resistentes al cambio de requisitos', 0], ['La OO se basa en conceptos del dominio, más estables que los algoritmos', 1], ['La OO solo sirve para sistemas de negocio pequeños', 0], ['En la OO el bloque de construcción es el procedimiento', 0]],
      e: 'La algorítmica produce sistemas FRÁGILES. La OO funciona en cualquier dominio, tamaño y complejidad, y su bloque es el objeto o clase.' },
    { u: 2, q: 'Sobre la ABSTRACCIÓN, ¿qué es correcto?',
      o: [['Existe una única abstracción correcta de cada objeto', 0], ['Es igual para todos los observadores', 0], ['Es un elemento menor del modelo de objetos', 0], ['Consiste en quedarse con las características esenciales para un propósito', 1], ['Es sinónimo de encapsulamiento', 0]],
      e: 'La abstracción depende de quién mira (gato: persona común, veterinario, biólogo). Es un elemento MAYOR.' },
    { u: 2, q: 'Sobre la relación de REALIZACIÓN, ¿qué es correcto?',
      o: [['Aparece entre una interfaz y las clases que la implementan', 1], ['Aparece entre un caso de uso y la colaboración que lo realiza', 1], ['Se dibuja con un rombo relleno', 0], ['Es la relación “es-un” entre dos clases concretas', 0], ['Un elemento especifica un contrato y otro se compromete a cumplirlo', 1]],
      e: 'Se dibuja con línea discontinua y punta de flecha vacía. El “es-un” entre clases es generalización.' },
    { u: 2, q: 'Sobre el modelo de dominio, ¿qué es correcto?',
      o: [['Describe los procesos y flujos del negocio', 0], ['Es un vocabulario estructurado del dominio', 1], ['Permite al equipo hablar el mismo idioma que el cliente', 1], ['Contiene las clases de diseño con sus métodos de implementación', 0], ['Solo puede construirse a partir de la ERS aprobada', 0]],
      e: 'NO describe procesos: describe COSAS y cómo se relacionan.' },
    { u: 2, q: 'En el ejemplo de la biblioteca con los patrones de Coad, ¿qué correspondencias son correctas?',
      o: [['Préstamo – Devolución → Transacción – TransacciónSubsiguiente', 1], ['Lector – Préstamo → Actor – Participante', 0], ['Libro – Ejemplar → Transacción – DetalleDeTransacción', 0], ['Pedido – Recepción → Ítem – ÍtemEspecífico', 0], ['Préstamo – Devolución → Lugar – Transacción', 0]],
      e: 'Lector–Préstamo es Participante–Transacción; Libro–Ejemplar es Ítem–ÍtemEspecífico; Pedido–Recepción es Transacción–TransacciónSubsiguiente.' },
    { u: 3, q: 'Según los niveles de granularidad de Pressman, ¿qué es correcto?',
      o: [['“Diseñar la arquitectura” es una acción', 1], ['“Ejecutar una prueba unitaria” es una actividad', 0], ['“Comunicación con los interesados” es una actividad', 1], ['“Ejecutar una prueba unitaria” es una tarea', 1], ['“Diseñar la arquitectura” es una tarea', 0]],
      e: 'Actividad (objetivo amplio) > acción (produce un producto de trabajo importante) > tarea (objetivo pequeño y bien definido).' },
    { u: 3, q: 'Sobre el Sprint en Scrum, ¿qué es correcto?',
      o: [['Dura como máximo 2 meses', 0], ['Si hay apuro, se puede bajar la calidad', 0], ['El alcance se puede aclarar y renegociar a medida que se aprende', 1], ['El Daily Scrum es un reporte de estado al Scrum Master', 0], ['La Sprint Review es una presentación formal sin interacción', 0]],
      e: 'El Sprint dura ≤ 1 mes, la calidad no baja, el Daily es planificación (no reporte) y la Review es una sesión de trabajo con feedback.' },
    { u: 3, q: '¿Cuáles son principios del desarrollo Lean?',
      o: [['Maximizar el trabajo en progreso', 0], ['Decidir lo antes posible', 0], ['Entregar lo más tarde posible', 0], ['Optimizar cada parte de forma aislada', 0], ['Documentar exhaustivamente antes de codificar', 0]],
      e: 'Ninguna: todas están invertidas. Los principios son eliminar desperdicio, amplificar aprendizaje, decidir lo más TARDE, entregar lo más RÁPIDO, potenciar al equipo, construir integridad y ver el TODO.' },
    { u: 3, q: 'Sobre Kanban, ¿qué es correcto según el material?',
      o: [['Trabaja con flujo continuo, sin sprints', 1], ['Scrum usa el Lead Time como su métrica principal', 0], ['Permite cambios en cualquier momento', 1], ['El límite WIP fija la cantidad mínima de ítems en DOING', 0], ['Kanban reemplaza a Lean', 0]],
      e: 'El límite de WiP es el MÁXIMO de elementos en progreso. El Lead Time es una métrica clave de Kanban. Kanban complementa a Lean, no lo reemplaza.' },
    { u: 3, q: 'Sobre fases y flujos de trabajo del PU, ¿qué es correcto?',
      o: [['Existe una etapa de pruebas al final del proyecto', 0], ['Se prueba desde la primera iteración', 1], ['El esfuerzo de requisitos llega a cero en construcción', 0], ['En cada fase se hace algo de todos los flujos, en proporciones distintas', 1], ['Las fases dividen el tiempo; los flujos, el tipo de trabajo', 1]],
      e: 'No existe “la etapa de pruebas”: existe una fase donde el esfuerzo de prueba es máximo. Requisitos decrece pero nunca llega a cero.' },
    { u: 3, q: 'Sobre la planificación en el PU, ¿qué es correcto?',
      o: [['El plan de la iteración actual está completamente detallado', 1], ['El plan de la siguiente iteración también está completamente detallado', 0], ['El plan de proyecto es detallado al máximo desde el principio', 0], ['El contenido del plan de iteración depende, entre otras cosas, de los riesgos a mitigar', 1], ['Conviene planificar en detalle 8 meses hacia adelante', 0]],
      e: 'Actual = completo; siguiente = a medio detallar; posteriores = esbozados. El plan de proyecto es grueso al principio y se precisa con el tiempo.' },
    { u: 5, q: 'Sobre las características de un buen documento ERS, ¿qué es correcto?',
      o: [['“Responde en menos de 2 segundos” es un requisito verificable', 1], ['“El sistema debe ser fácil de usar” es un requisito verificable', 0], ['Trazable significa que se vincula a su origen y a los artefactos que lo implementan', 1], ['“No ambiguo” significa que no hay contradicciones entre requisitos', 0], ['“Consistente” significa que cada requisito tiene una única interpretación', 0]],
      e: '“Fácil” no es verificable. Consistente = sin contradicciones; no ambiguo = una única interpretación (están cruzadas en las opciones).' }
  ],

  // ======================= EXTREMO =======================
  extremo: [
    { u: 1, q: 'Un banco tiene un sistema COBOL que funciona hace 30 años sin fallas graves. Nadie lo entiende del todo y ahora hay que exponerlo como API para una app móvil. ¿Qué es correcto?',
      o: [['Es un caso típico de software heredado', 1], ['La estrategia de “envolver con una capa nueva” encaja con el escenario', 1], ['Que sea confiable contradice que sea legacy', 0], ['La decisión sobre qué hacer es estratégica, no solo técnica', 1], ['Hay que reescribirlo porque su lógica de negocio ya no es válida', 0]],
      e: 'La confiabilidad es justamente parte de la paradoja del legacy. Nada indica que la lógica de negocio no sea válida; funciona bien y hay que adaptarlo a interfaces nuevas → envolver.' },
    { u: 1, q: 'Un equipo afirma: “Ya tenemos el 100% del código, el sistema está terminado”. ¿Qué es correcto?',
      o: [['No necesariamente está el 100% del software', 1], ['El software es solo el código ejecutable, así que la afirmación es correcta', 0], ['Refleja un mito del desarrollador', 1], ['Es un mito del cliente porque subestima el costo del cambio', 0], ['Si el código compila y pasa las pruebas, el sistema está completo según la definición integral', 0]],
      e: 'Faltan configuración, datos de producción, manuales y documentación. “Cuando el programa funciona el trabajo está terminado” es un mito del desarrollador.' },
    { u: 1, q: 'Sobre el software de un marcapasos, ¿qué es correcto?',
      o: [['Es software empotrado', 1], ['La confiabilidad está por encima de los demás atributos', 1], ['Conviene priorizar usabilidad y escalabilidad, como en una red social', 0], ['Al vivir en un dispositivo tiene pocas restricciones de memoria y energía', 0], ['Como el software no se desgasta, no puede fallar después de instalado', 0]],
      e: 'El empotrado tiene restricciones FUERTES de memoria, energía y tiempo real. Que no se desgaste no significa que no tenga defectos.' },
    { u: 1, q: 'Un equipo pasa de 4 a 6 desarrolladores. Respecto de los canales de comunicación, ¿qué es correcto?',
      o: [['Pasan de 6 a 15', 1], ['Pasan de 4 a 6', 0], ['Pasan de 6 a 12', 0], ['Crecen de forma lineal con la cantidad de personas', 0], ['Crecen de forma cuadrática', 1]],
      e: 'Fórmula N(N-1)/2: con 4 personas son 6 canales; con 6 personas, 15.' },
    { u: 1, q: 'Sobre la definición IEEE, ¿qué interpretaciones son correctas?',
      o: [['“Cuantificable” significa que el proceso debe estar automatizado', 0], ['“Disciplinado” significa seguir el método salvo cuando hay presión de tiempo', 0], ['La definición cubre solo el desarrollo, no la operación', 0], ['“Sistemático” significa improvisar cada paso según la situación', 0], ['Medir es opcional si el equipo es experimentado', 0]],
      e: 'Ninguna. Cuantificable = se puede medir; disciplinado = se sigue AUN bajo presión; cubre desarrollo, operación y mantenimiento; sistemático = hay método, no improvisación. Sin medición es “artesanía prolija”.' },
    { u: 1, q: 'Una empresa necesita conectar su mainframe con una app web para clientes, y los clientes deben poder confiar en que sus datos no se pierden. ¿Qué retos del siglo XXI aparecen en esta situación?',
      o: [['Heterogeneidad', 1], ['Confianza', 1], ['Portabilidad', 0], ['Escalabilidad', 0], ['Usabilidad', 0]],
      e: 'Integrar sistemas heredados con plataformas nuevas es heterogeneidad; demostrar que se puede confiar en un sistema web es confianza. Portabilidad, escalabilidad y usabilidad no están entre los tres retos del siglo XXI (heterogeneidad, entrega y confianza).' },
    { u: 2, q: 'Cada Factura tiene varios DetalleDeFactura; si se elimina la factura se eliminan sus detalles. Cada detalle referencia un Producto que existe por sí mismo. ¿Qué es correcto?',
      o: [['Factura – DetalleDeFactura es composición', 1], ['Factura – DetalleDeFactura se dibuja con rombo hueco', 0], ['DetalleDeFactura – Producto es composición', 0], ['Según Coad, Producto – DetalleDeFactura es Ítem – ÍtemEspecífico', 0], ['Según Coad, Factura – DetalleDeFactura es Transacción – DetalleDeTransacción', 1]],
      e: 'La composición usa rombo RELLENO. El Producto existe independientemente, así que no es composición; en Coad es Ítem – DetalleDeTransacción.' },
    { u: 2, q: 'ClienteMayorista y ClienteMinorista comparten los atributos y el comportamiento de Cliente. ¿Qué es correcto?',
      o: [['Es una relación de agregación', 0], ['Se dibuja con un rombo relleno del lado de Cliente', 0], ['Es una dependencia porque Cliente se pasa por parámetro', 0], ['Es una realización porque Cliente es un contrato', 0], ['Es una relación “parte-de”', 0]],
      e: 'Ninguna. Es GENERALIZACIÓN (herencia, “es-un”), dibujada con triángulo hueco hacia Cliente.' },
    { u: 2, q: 'ServicioPago recibe un objeto Banco como parámetro en su método pagar(), pero no lo guarda como atributo. ¿Qué es correcto?',
      o: [['Es una dependencia', 1], ['Es una asociación con multiplicidad 1..*', 0], ['Es una composición', 0], ['Se dibuja con línea continua y rombo', 0], ['Es una realización', 0]],
      e: 'Usa a Banco sin poseerlo ni tener vínculo permanente → dependencia (línea punteada con flecha abierta).' },
    { u: 2, q: 'Dos objetos CuentaBancaria tienen el mismo titular y el mismo saldo. ¿Qué es correcto?',
      o: [['Son el mismo objeto porque tienen el mismo estado', 0], ['Su identidad depende del valor de sus atributos', 0], ['Si cambia el saldo de uno, cambia el del otro', 0], ['Para distinguirlos es obligatorio agregarles un atributo “id”', 0], ['El estado de un objeto es lo que el objeto hace', 0]],
      e: 'Ninguna. La IDENTIDAD distingue a los objetos aunque tengan el mismo estado, y se preserva durante su ciclo de vida. El estado es lo que el objeto SABE; lo que hace es su comportamiento.' },
    { u: 3, q: 'Una ONG necesita una app; los requisitos cambian cada semana y el cliente puede participar a diario. Según la comparación tradicional vs ágil, ¿qué es correcto?',
      o: [['Conviene un enfoque ágil', 1], ['Conviene congelar los requisitos lo antes posible', 0], ['Encaja una entrega frecuente e incremental', 1], ['El cliente debería involucrarse solo al inicio y al final', 0], ['Hay que planificar en detalle todo el proyecto al comienzo', 0]],
      e: 'Alta incertidumbre y cliente disponible → ágil: entrega frecuente, planificación adaptativa y participación continua del cliente.' },
    { u: 3, q: 'Sobre el Manifiesto Ágil, ¿qué es correcto?',
      o: [['Rechaza la documentación', 0], ['Valora los elementos de la derecha, aunque menos que los de la izquierda', 1], ['Recomienda entregar software entre 2 y 6 meses', 0], ['La medida principal de progreso son las horas trabajadas', 0], ['Propone horas extra permanentes para cumplir las fechas', 0]],
      e: 'Se entrega entre 2 semanas y 2 meses; el progreso se mide con software funcionando; se busca un ritmo sostenible.' },
    { u: 3, q: 'Durante un Sprint, el Product Owner quiere agregar una funcionalidad que pone en riesgo el Objetivo del Sprint. ¿Qué es correcto?',
      o: [['No se permiten cambios que pongan en riesgo el objetivo del Sprint', 1], ['Se puede bajar la calidad para llegar con todo', 0], ['El alcance puede aclararse y renegociarse a medida que se aprende', 1], ['Lo decide el Scrum Master como jefe del equipo', 0], ['Se resuelve en el Daily Scrum replanificando todo el Sprint', 0]],
      e: 'Restricciones del Sprint: no se aceptan cambios que pongan en riesgo el objetivo y la calidad no baja; el alcance sí puede renegociarse. El SM no es jefe.' },
    { u: 3, q: 'Un tablero tiene 9 tarjetas en DOING, muchas detenidas hace días, y el tiempo de entrega (Lead Time) creció. Según Kanban, ¿qué es correcto?',
      o: [['Falta (o no se respeta) un límite de WIP', 1], ['Hay que hacer políticas explícitas para no dejar tareas dormidas en DOING', 1], ['La solución es pasar a sprints fijos de 4 semanas', 0], ['Más tareas en paralelo siempre mejoran el tiempo de entrega', 0], ['La métrica a mirar es la velocidad en puntos por sprint', 0]],
      e: 'Limitar el WiP y hacer explícitas las políticas son prácticas generales de Kanban. Kanban no usa sprints, y su métrica clave es el Lead Time, no la velocidad en puntos.' },
    { u: 3, q: 'Proyecto de 6 meses: el equipo implementó el 5-10% de la funcionalidad, eligiendo la arquitectónicamente significativa, y al terminar entregará una propuesta firme de costos y plazos. ¿Qué es correcto?',
      o: [['Están en la fase de Inicio', 0], ['Están en la fase de Elaboración', 1], ['Están en la fase de Construcción', 0], ['Están en la fase de Transición', 0], ['Esta fase termina en la capacidad operativa inicial', 0]],
      e: 'Es Elaboración (línea base de la arquitectura, sobre un 80% de los requisitos capturados, estimación para comprometerse al desarrollo). La capacidad operativa inicial cierra Construcción.' },
    { u: 3, q: 'Un equipo dice usar PU, pero hace todo el análisis el primer mes, el diseño el segundo y prueba solo en el último. ¿Qué es correcto?',
      o: [['Es una cascada disfrazada', 1], ['Es correcto, porque en el PU las fases coinciden con los flujos', 0], ['En el PU la prueba empieza desde la primera iteración', 1], ['El equipo confunde fases (tiempo) con flujos (tipo de trabajo)', 1], ['Es válido siempre que haya cuatro fases con los nombres correctos', 0]],
      e: 'Fases y flujos son dimensiones independientes; en cada fase se hace algo de todos los flujos. Separarlos por etapas es cascada.' },
    { u: 4, q: 'Juan es a la vez arquitecto e ingeniero de casos de uso, y el rol de ingeniero de componentes lo cubren tres personas. ¿Qué es correcto?',
      o: [['Es válido en el PU', 1], ['Viola el PU: cada rol debe estar a cargo de una persona distinta', 0], ['Un trabajador es un rol, no una persona', 1], ['Un trabajador equivale a un cargo que hay que contratar', 0], ['Un artefacto es la persona responsable de una actividad', 0]],
      e: 'Una persona puede tener varios roles y un rol puede ser cubierto por varias personas. Un artefacto es un producto del proceso.' },
    { u: 5, q: 'Clasificá: “El sistema debe usar solo software open source”.',
      o: [['Es un requisito no funcional', 1], ['Es un requisito organizacional', 1], ['Es un requisito externo', 0], ['Es un requisito funcional', 0], ['Es un requisito del producto', 0]],
      e: 'Es no funcional organizacional: impuesto por políticas del cliente o del desarrollador. Los externos son legales o de interoperabilidad; los del producto son rendimiento, usabilidad, etc.' },
    { u: 5, q: '“Hacer pedido” siempre valida al usuario; si el pedido es urgente, en el punto “establecer prioridad” se inserta “Hacer pedido urgente”; y “Cobrar pedido” puede ser en efectivo o con tarjeta. ¿Qué es correcto?',
      o: [['Hacer pedido → Validar usuario es <<include>>', 1], ['Hacer pedido urgente → Hacer pedido es <<extend>>', 1], ['Cobrar en efectivo / con tarjeta respecto de Cobrar pedido es generalización', 1], ['En la extensión la flecha va desde el caso base hacia el que extiende', 0], ['En la inclusión el caso base no sabe que incluye a otro', 0]],
      e: 'En <<extend>> la flecha va del que extiende hacia el base, y es el base el que “ni se entera”. En <<include>> el base lo llama explícitamente.' },
    { u: 5, q: 'Un sistema tiene 20 casos de uso y cada uno se expande en unos 10 escenarios. ¿Qué es correcto?',
      o: [['Se derivan unos 20 casos de prueba, uno por caso de uso', 0], ['Se deriva un caso de prueba por escenario (unos 200)', 1], ['Un escenario es una instancia de un caso de uso', 1], ['Un caso de uso describe una única secuencia de acciones', 0], ['No hace falta priorizar las pruebas porque se derivan automáticamente', 0]],
      e: 'Un caso de uso describe un CONJUNTO de secuencias; cada camino es un escenario. Las pruebas se multiplican, por eso hay que priorizarlas.' }
  ]
};
